# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0858a313d323d8cd18f4bce78b69eb4"
name = "fuzzaltytics"
application_url = "http://localhost:8080"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_draft_orders,read_draft_orders,read_orders,write_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"
